# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcollection',
            name='position',
            field=models.BigIntegerField(),
        ),
    ]
